eng_to_idx = {'snowe_haengsa':0,
              'snowe_haksa':1,
              'snowe_haksaeng':2,
              'snowe_janghak':3,
              'snowe_mojip':4,
              'snowe_system':5,
              'job_chuiup':6,
              'job_gyoyuk':7,
              'job_haengsa':8,
              'job_internship':9,
              'job_mentor':10}

idx_to_kor = {0:"행사",
              1:"학사",
              2:"학생",
              3:"장학",
              4:"모집",
              5:"시스템",
              6:"취업",
              7:"교육",
              8:"행사",
              9:"인턴쉽",
              10:"멘토"}